/// ═════════════════════════════════════════════════════════════
/// AUTO-GENERATED by BotForge — DO NOT EDIT MANUALLY
/// Organisation: test-mobile-response (24532c4a-1845-4ca5-b472-313e579df8a6)
/// Generated: 2026-05-05T11:46:46.972Z
/// Chatbot ID: ee0af600-1cb9-448e-bd6b-051dcc322daa
/// ═════════════════════════════════════════════════════════════
library;

class AppConfig {
  AppConfig._();

  // ── Brand Identity ──────────────────────────────────────────────
  static const String businessName   = 'test-mobile-response';
  static const String tagline        = '';
  static const String botName        = 'Acme';
  static const String botRole        = 'Customer Experience Assistant';
  static const String welcomeMessage = 'Hi there! 👋 I\'m $botName, your personal assistant at $businessName. How can I help you today?';

  static const List<String> quickReplies = [
    '💰 Pricing & Plans',
    '🛠️ Our Services',
    '📞 Contact Support'
  ];

  // ── Visuals ──────────────────────────────────────────────────────
  static const String primaryColorHex = '#e85518';
  static const String accentColorHex  = '#0f172a';
  static const String botAvatarAsset  = 'assets/images/bot_avatar.png';
  static const String logoAsset       = 'assets/images/logo.png';

  // ── Backend ──────────────────────────────────────────────────────
  static const String apiBaseUrl     = 'https://chat-dev-main-backend-latest-7hxy.onrender.com';
  static const String chatEndpoint   = '/chatbots/mobile';
  static const String organisationId = '24532c4a-1845-4ca5-b472-313e579df8a6';
  static const String chatbotId = 'ee0af600-1cb9-448e-bd6b-051dcc322daa';
  static const String botCreatorUrl = 'https://botcreator-1.onrender.com';
  static const String apiKey = 'D6AjXcOrYSwPgd6QYu2CWLv371J1Ol2i';

  // ── Chat Session ────────────────────────────────────────────────
  static const String chatId = '';  // Generated on first chat

  // ── Business Hours ───────────────────────────────────────────────
  static const bool   showBusinessHours = false;
  static const String businessHours     = '';
  static const String offlineMessage    =
      'We are currently outside business hours. I will still do my best to help, '
      'but a human agent will follow up. 🌙';

  // ── Social / Contact ─────────────────────────────────────────────
  static const String whatsappNumber  = '';
  static const String telegramHandle  = '';
  static const String supportEmail    = '';
  static const String websiteUrl      = '';

  // ── Feature Flags ─────────────────────────────────────────────────
  static const bool enableFileAttachments = true;
  static const bool enableVoiceMessages   = false;
  static const bool enableRatings         = true;
  static const bool enableTypingIndicator = true;
  static const bool enableReadReceipts    = true;
}